# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf2f7233986a2550f1a9fb9a2581dd506c3c96364ee010432a293081ec93677b0013ba9b0377888824251f9b87814b11498a39896c8816ffe03d7c641e67bfaf

test:
  secret_key_base: d523ea7dda238176671d1c9e9a7c87c9ee71f404c894007066e3d0b7be32960e65bf8edd0e0feaa33534915d2b4e8603128867ff502ea4623f6429a5533f5644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
